# GENERATED by tools/flow.py from flow.toml. Do not edit; edit flow.toml and run: python3 tools/flow.py render
.PHONY: fmt lint typecheck test check
fmt:        ## 整形（ファイルを書き換える。失敗しない）
	@echo 'flow.toml is incomplete: `formatter` is not decided. Run /setup (or edit flow.toml) and then: python3 tools/flow.py render' >&2; exit 1
lint:       ## Linter（違反があれば非0）
	@echo 'flow.toml is incomplete: `linter` is not decided. Run /setup (or edit flow.toml) and then: python3 tools/flow.py render' >&2; exit 1
typecheck:  ## 型（違反があれば非0）
	@echo 'flow.toml is incomplete: `typechecker` is not decided. Run /setup (or edit flow.toml) and then: python3 tools/flow.py render' >&2; exit 1
test:       ## テスト（失敗があれば非0）
	@echo 'flow.toml is incomplete: `test_runner` is not decided. Run /setup (or edit flow.toml) and then: python3 tools/flow.py render' >&2; exit 1
check: fmt lint typecheck test
